{{- include "prechecks" . -}}
# apiVersion: v1
# data:
#   profile-name: {{ .Values.dex.defaultUserProfile }}
#   user: {{ .Values.dex.defaultUserEmail }}
# kind: ConfigMap
# metadata:
#   name: default-install-config-5cbhhbttg4
#   annotations:
#     "helm.sh/hook": post-install
#     "helm.sh/hook-weight": "10"
#     "helm.sh/hook-delete-policy": hook-succeeded
# ---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: {{ .Values.dex.defaultUserProfile }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    # profile should not be deleted
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  owner:
    kind: User
    name: {{ .Values.dex.defaultUserEmail }}
