{{- include "prechecks" . -}}
apiVersion: v1
data:
  profile-name: {{ .Values.defaultUserProfile }}
  user: {{ .Values.defaultUserEmail }}
kind: ConfigMap
metadata:
  name: default-install-config-5cbhhbttg4
---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: {{ .Values.defaultUserProfile }}
spec:
  owner:
    kind: User
    name: {{ .Values.defaultUserEmail }}
