apiVersion: v2
name: knative-serving
version: "v1.2.5"
kubeVersion: ">=1.17.0"
description: "knative serving for kubeflow-chart."
type: application
sources:
  - https://github.com/alauda/kubeflow-chart
maintainers:
  - name: typhoonzero
    email: typhoonzero1986@gmail.com
appVersion: "v1.2.5"
