apiVersion: v2
name: dex
version: "2.31.2"
kubeVersion: ">=1.20.0"
description: dex for kubeflow.
type: application
keywords:
  - "cert manager"
sources:
  - https://github.com/alauda/kubeflow-chart
maintainers:
  - name: typhoonzero
    email: typhoonzero1986@gmail.com
appVersion: "2.31.2"
