dryRun: false

namespace: kubeflow

# Set enableIngress to true to use Kubernetes ingress to access Kubeflow.
# else, you need to use istio-ingressgateway service.
enableIngress: false
# kubeflowHost is the VirtualService host setting,
# it should be a FQDN formated string.
# - If you are using ingress, must set kubeflowHost to a valid domain name.
# - If you are using IP to access Kubeflow, set kubeflowHost to "*" and enableIngress to false.
kubeflowHost: "*"
# kubeflowSitePrefix only supports "/" currently
kubeflowSitePrefix: "/"
# Setup tlsCrt and tlsKey to support HTTPS access (base64 encoded).
tlsCrt: ""
tlsKey: ""

# Dex auth configurations
oidcAuthURL: /dex/auth
oidcProvider: http://dex.auth.svc.cluster.local:5556/dex
skipAuthURI: "/dex"
useridClaim: email
useridHeader: kubeflow-userid
useridPrefix: "\"\""
oidcScopes: "profile email groups"

# Set minio.enabled = true to use embeded single node MinIO test deployment.
minio:
  enabled: true
  kfpMinioImage: gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
# If you are not using the embeded deployment, setup minioAK and minioSK below.
# minioAK: 
# minioSK: 

# Set dex.enabled = true to use embeded Dex deployment.
# If you are using your own Dex server, 
# you need to setup below clientID, clientSecret, defaultUserEmail
dex:
  enabled: true
  oidcRedirectURL: /login/oidc
  defaultUserEmail: user@example.com      
  # clientID: a3ViZWZsb3ctb2lkYy1hdXRoc2VydmljZQ==
  # clientSecret: WlhoaGJYQnNaUzFoY0hBdGMyVmpjbVYw

# The default namespace bind to the default user:
defaultUserProfile: kubeflow-user-example-com
notebookAccessPipelineDesc: "Allow access pipeline"

# ----------------------------------------------------
# Images
# ----------------------------------------------------
admissionWebhookImage: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook:v1.4
jupyterWebAppImage: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.4
notebookControllerImage: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller:v1.4
notebookImageScipy: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:v1.4
notebookImagePytorch: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-full:v1.4
notebookImagePytorchCuda: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-pytorch-cuda-full:v1.4
notebookImageTensorflow: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-full:v1.4
notebookImageTensorflowCuda: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-tensorflow-cuda-full:v1.4

oidcAuthServiceImage: gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef
centralDashboardImage: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.4
kfamAccessManagementImage: public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.4
kfamProfileControllerImage: public.ecr.aws/j1r0q0g6/notebooks/profile-controller:v1.4
volumesWebAppImage: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app:v1.4
notebookImageCodeserverPython: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:v1.4
notebookImageRstudioTidyverse: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:v1.4

# kfpVersion is the version of Kubeflow Pipeline images
kfpVersion: "1.7.0"

kfpApiServerImageAndTag: gcr.io/ml-pipeline/api-server:1.7.0

# below images uses kfpVersion as version tag:
kfpVisualizationServerImage: gcr.io/ml-pipeline/visualization-server
kfpFrontendImage: gcr.io/ml-pipeline/frontend
kfpViewerCrdControllerImage: gcr.io/ml-pipeline/viewer-crd-controller
kfpScheduledWorkflowImage: gcr.io/ml-pipeline/scheduledworkflow
kfpPersistenceAgentImage: gcr.io/ml-pipeline/persistenceagent
kfpMetadataWriterImage: gcr.io/ml-pipeline/metadata-writer
kfpMetadataEnvoyImage: gcr.io/ml-pipeline/metadata-envoy
kfpCacheServerImage: gcr.io/ml-pipeline/cache-server
kfpCacheDeployerImage: gcr.io/ml-pipeline/cache-deployer

# pipeline images using unique tags:
kfpMlMetadataStoreServerImage: gcr.io/tfx-oss-public/ml_metadata_store_server:1.0.0
kfpCacheImage: gcr.io/google-containers/busybox
kfpArgoExecImage: gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance
kfpArgoControllerImage: gcr.io/ml-pipeline/workflow-controller:v3.1.6-patch-license-compliance
kfpMetaControllerImage: metacontroller/metacontroller:v0.3.0
kfpMysqlImage: gcr.io/ml-pipeline/mysql:5.7
kfpPythonImage: python:3.7

# KFServing
kfsVersion: "v0.6.1"
kfsAgentImage: kfserving/agent
kfsAlibiExplainerImage: kfserving/alibi-explainer
kfsAixExplainer: kfserving/aix-explainer
kfsArtExplainer: kfserving/art-explainer

kfsTensorflowImage: tensorflow/serving
kfsTensorflowImageVersion: "1.14.0"
kfsTensorflowImageGpuVersion: "1.14.0-gpu"

kfsOnnxImage: mcr.microsoft.com/onnxruntime/server
kfsOnnxImageVersion: "v1.0.0"

kfsSkLearnImage: kfserving/sklearnserver
kfsSkLearnImageVersion: "v0.6.1"

kfsSeldonioImage: docker.io/seldonio/mlserver
kfsSeldonioImageVersion: "0.2.1"

kfsXgbserverImage: kfserving/xgbserver
kfsXgbserverImageVersion: "v0.6.1"

kfsPytorchImage: kfserving/pytorchserver
kfsPytorchImageVersion: "v0.6.1"
kfsPytorchImageGpuVersion: "v0.6.1-gpu"

kfsTorchServeImage: pytorch/torchserve-kfs
kfsTorchServeImageVersion: "0.4.0"
kfsTorchServeImageGpuVersion: "0.4.0-gpu"

kfsTritonImage: nvcr.io/nvidia/tritonserver
kfsTritonImageVersion: "20.08-py3"

kfsPmmlserverImage: kfserving/pmmlserver
kfsPmmlserverImageVersion: "v0.6.1"

kfsLgbserverImage: kfserving/lgbserver
kfsLgbserverImageVersion: "v0.6.1"

kfsPaddleserverImage: kfserving/paddleserver
kfsPaddleserverImageVersion: "v0.6.1"

kfsStorageInitializerImage: kfserving/storage-initializer

kfsModelsWebAppImage: kfserving/models-web-app
kfsControllerImage: kfserving/kfserving-controller
kfsKubeRbacProxyImage: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0

# knative
knativeVersion: "v0.22.1"

# NOTE: kubeflow's knative installation uses digest to pull these images.
# @sha256:0b8e031170354950f3395876961452af1c62f7ab5161c9e71867392c11881962
knativeServingQueueImage: gcr.io/knative-releases/knative.dev/serving/cmd/queue
# @sha256:fed92af8b9779c97482906db8857f27b5d4826708b75d0298aa30fad8900671f
knativeServingActivatorImage: gcr.io/knative-releases/knative.dev/serving/cmd/activator
# @sha256:bc5ae3090ab0322ed0e4f9efddb60fa85f6ff3a29156411d24d0e4764b18eba7
knativeServingAutoscalerImage: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
# @sha256:bd7c6350e5d5c4edaa197a86fb96cff78bdd3e61f33fcb77aa60930de0ec0827
knativeServingControllerImage: gcr.io/knative-releases/knative.dev/serving/cmd/controller
# @sha256:1e371db6b1a9f9265fc7a55d15d98c935c0c28925ffde351fb3b93f331c5a08e
knativeNetWebhookImage: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
# @sha256:ff8680da52ef47b8573ebc3393cbfa2f0f14b05c1e02232807f22699adbef57a
knativeNetControllerImage: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
# @sha256:6f41d379f1aacdfbb8f6d4f539e1769040e4f01bff3ad9c249b427e54dc56ea8
knativeServingWebhookImage: gcr.io/knative-releases/knative.dev/serving/cmd/webhook

# Used by templates/cluster-local-gateway.yaml for knative istio confs.
knativeProxyvImage: docker.io/istio/proxyv2:1.9.6
# Configmap used by istio, for creating kfserving "cluster-local-gateway".
# You may use `kubectl -n istio-system get configmap` to confirm.
knativeIstioConfigmap: istio
# istio configuration "ISTIO_META_CLUSTER_ID" used by kfserving cluster-local-gateway.
# Default: Kubernetes
istioMetaClusterID: Kubernetes

# training operators
trainingOperatorImage: public.ecr.aws/j1r0q0g6/training/training-operator:760ac1171dd30039a7363ffa03c77454bd714da5
mpiOperatorImage: mpioperator/mpi-operator:0.3.0
mpiOperatorKubectlDeliveryImage: mpioperator/kubectl-delivery:latest

# Tensorboard
tensorboardControllerImage: public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller:v1.4
tensorboardWebAppImage: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app:v1.4
